<?php
if (empty($review)) {
    for ($i = 0; $i < 37; $i++) {
        $csv->addField('');
    }
} else {
    $csv->addField(flag_output($review['signs_flag']));
    $csv->addField(flag_output($review['diagnose_flag']));
    $csv->addField(flag_output($review['prescribed_flag']));
    $csv->addField($review['onset_date']);
    $csv->addField($review['congestion']);
    $csv->addField(flag_output($review['echo_flag']));
    $csv->addField($review['lvef']);
    $csv->addField(flag_output($review['low_lvef_flag']));
    $csv->addField(flag_output($review['wma_flag']));
    $csv->addField(flag_output($review['lvcd_flag']));
    $csv->addField(flag_output($review['dd_flag']));
    $csv->addField(flag_output($review['msvd_flag']));
    $csv->addField($review['lab']);
    $csv->addField($review['hf_type']);
    $csv->addField($review['classification']);
    $csv->addField(flag_output($review['ischemic_flag']));
    $csv->addField(flag_output($review['nonischemic_flag']));
    $csv->addField(flag_output($review['ni_valvular_flag']));
    $csv->addField(flag_output($review['ni_infiltrative_flag']));
    $csv->addField(flag_output($review['ni_im_flag']));
    $csv->addField(flag_output($review['ni_obstructive_flag']));
    $csv->addField(flag_output($review['ni_recreational_flag']));
    $csv->addField(flag_output($review['ni_prescription_flag']));
    $csv->addField(flag_output($review['ni_hypertensive_flag']));
    $csv->addField(flag_output($review['ni_renal_flag']));
    $csv->addField(flag_output($review['ni_cardiomyopathy_flag']));
    $csv->addField(flag_output($review['ni_covid_flag']));
    $csv->addField(flag_output($review['ni_sepsis_flag']));
    $csv->addField(flag_output($review['ni_metabolic_flag']));
    $csv->addField(flag_output($review['ni_pd_flag']));
    $csv->addField(flag_output($review['ni_hypertrophic_flag']));
    $csv->addField(flag_output($review['ni_other_flag']));
    $csv->addField($review['ni_other']);
    $csv->addField(flag_output($review['unknown_flag']));
    $csv->addField($review['presentation']);
    $csv->addField(flag_output($review['more_info_flag']));
    $csv->addField($review['need_more']);
}
?>
