--
-- The `patients_view` view is created by init/06-create-patients-view.sh
-- after the underlying `uw_patients2` table (init/02-schema.sql) and the
-- FEDERATED proxy for `cnics_data.Patient` are in place. This file used
-- to contain a placeholder stub VIEW over the legacy `patients` table;
-- that stub has been removed along with the `patients` table itself.
--
