services:
  mariadb:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql
      - logs-data:/var/log/mysql
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - internal

  backend:
    build: ./flask_backend
    environment:
      DB_HOST: mariadb
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: 3000
    depends_on:
      - mariadb
    ports:
      - "3001:3000"
    networks:
      - internal

  web:
    build: ./frontend
    environment:
      VITE_API_URL: http://localhost:3001
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - internal
      

volumes:
  logs-data:
  mariadb-data:

networks:
  internal:
