version: "3.8"
services:
  mariadb:
    image: mariadb:10.5
    restart: unless-stopped
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: $Satinder.96
      MYSQL_DATABASE: $cnics_mci
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build: ./flask_backend
    environment:
      - DB_HOST=mariadb
      - DB_USER=$root
      - DB_PASSWORD=$Satinder.96
      - DB_NAME=$cnics_mci
    depends_on:
      - mariadb
    ports:
      - "3001:3000"

  web:
    build: ./frontend
    environment:
      - VITE_API_URL=http://backend:3000
    ports:
      - "3000:3000"

volumes:
  db_data:

